# Generated by Django 2.1.2 on 2018-10-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airport_code',
        ),
    ]
