# Generated by Django 2.1.2 on 2018-10-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_airline_airport_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='price',
            field=models.IntegerField(default=220),
        ),
    ]
