# Generated by Django 2.1.2 on 2018-10-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_journey_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='price',
            field=models.CharField(max_length=128),
        ),
    ]
