# Generated by Django 2.1.2 on 2018-10-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20181021_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='flag',
            field=models.IntegerField(default=1),
        ),
    ]
