# Generated by Django 2.1.2 on 2018-10-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_journey_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='flag',
        ),
        migrations.AddField(
            model_name='journey',
            name='journey_type',
            field=models.CharField(default='One Way', max_length=128),
        ),
    ]
